"""add_notification_type_and_donation_id_to_notification_log

Revision ID: b2faddcc9420
Revises: c3b6e5a7125b
Create Date: 2026-09-12 19:26:52.116519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2faddcc9420'
down_revision: Union[str, Sequence[str], None] = 'c3b6e5a7125b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_logs', sa.Column('notification_type', sa.String(length=50), nullable=True))
    op.add_column('notification_logs', sa.Column('related_donation_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_logs', 'related_donation_id')
    op.drop_column('notification_logs', 'notification_type')
    # ### end Alembic commands ###
