"""Add FridayBulletin table

Revision ID: c3b6e5a7125b
Revises: 05fb684bb43d
Create Date: 2026-09-11 23:05:07.126882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b6e5a7125b'
down_revision: Union[str, Sequence[str], None] = '05fb684bb43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friday_bulletins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('issue_number', sa.String(length=50), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=False),
    sa.Column('cover_image_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('donations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_donations_is_deleted'), 'donations', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_is_deleted'), table_name='donations')
    op.alter_column('donations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_table('friday_bulletins')
    # ### end Alembic commands ###
